USE [DSS]
GO

CREATE PROCEDURE [dbo].[SP_tbProduto]
 @DROP CHAR(1)
 AS
	IF @DROP = '1' 
	BEGIN
		IF (EXISTS(SELECT name FROM SYS.objects WHERE NAME = 'tbProduto'))
			BEGIN
				DROP TABLE tbProduto
				CREATE TABLE tbProduto (
					COD_PROD VARCHAR(15) PRIMARY KEY,
					DESC_PROD VARCHAR(60) NOT NULL,
					CODBAR_PROD VARCHAR(44),
					VLR_CUSTO DECIMAL(16,2) DEFAULT 0,
					VLR_VENDA DECIMAL(16,2) DEFAULT 0,
					QTD_MIN INTEGER DEFAULT 0,
					PESO_PROD DECIMAL(14,3) DEFAULT 0,
					BLQL_PROD CHAR(1) DEFAULT 2,
					COD_TAM VARCHAR(6),
					ID_ARM INT,
					ID_CATEG INT,
					ID_COR INT,
					ID_FAB INT,
					ID_UM INT,
					CONSTRAINT FK_IDARM		FOREIGN KEY (ID_ARM)	REFERENCES tbArmazem	(ID_ARM),
					CONSTRAINT FK_IDCATEG	FOREIGN KEY (ID_CATEG)	REFERENCES tbCategoria	(ID_CATEG),
					CONSTRAINT FK_IDCORES	FOREIGN KEY (ID_COR)	REFERENCES tbCores		(ID_COR),
					CONSTRAINT FK_IDFAB		FOREIGN KEY (ID_FAB)	REFERENCES tbFabricante (ID_FAB),
					CONSTRAINT FK_CODTAM	FOREIGN KEY (COD_TAM)	REFERENCES tbTamanho	(COD_TAM),
					CONSTRAINT FK_IDUM		FOREIGN KEY (ID_UM)		REFERENCES tbUnidMed	(ID_UM)
				)
			END
		ELSE
			BEGIN
				CREATE TABLE tbProduto (
					COD_PROD VARCHAR(15) PRIMARY KEY,
					DESC_PROD VARCHAR(60) NOT NULL,
					CODBAR_PROD VARCHAR(44),
					VLR_CUSTO DECIMAL(16,2) DEFAULT 0,
					VLR_VENDA DECIMAL(16,2) DEFAULT 0,
					QTD_MIN INTEGER DEFAULT 0,
					PESO_PROD DECIMAL(14,3) DEFAULT 0,
					BLQL_PROD CHAR(1) DEFAULT 2,
					COD_TAM VARCHAR(6),
					ID_ARM INT,
					ID_CATEG INT,
					ID_COR INT,
					ID_FAB INT,
					ID_UM INT,
					CONSTRAINT FK_IDARM		FOREIGN KEY (ID_ARM)	REFERENCES tbArmazem	(ID_ARM),
					CONSTRAINT FK_IDCATEG	FOREIGN KEY (ID_CATEG)	REFERENCES tbCategoria	(ID_CATEG),
					CONSTRAINT FK_IDCORES	FOREIGN KEY (ID_COR)	REFERENCES tbCores		(ID_COR),
					CONSTRAINT FK_IDFAB		FOREIGN KEY (ID_FAB)	REFERENCES tbFabricante (ID_FAB),
					CONSTRAINT FK_CODTAM	FOREIGN KEY (COD_TAM)	REFERENCES tbTamanho	(COD_TAM),
					CONSTRAINT FK_IDUM		FOREIGN KEY (ID_UM)		REFERENCES tbUnidMed	(ID_UM)
				)
			END
		END
	ELSE
		DROP TABLE tbProduto
GO


